oauth2:
  image: quay.io/keycloak/keycloak:22.0.5
  command:
    - start-dev
  environment:
    - KEYCLOAK_ADMIN=eternal
    - KEYCLOAK_ADMIN_PASSWORD=eternal123
  ports:
    - "8081:8080"


    # docker run -it -p "8081:8080" -e 'KEYCLOAK_ADMIN=eternal' -e 'KEYCLOAK_ADMIN_PASSWORD=eternal123' quay.io/keycloak/keycloak:21.0.2 start-dev